export enum Lesao {
  PARAPLEGIA = 'PARAPLEGIA',

  TETRAPLEGIA = 'TETRAPLEGIA',

  AMPUTADO = 'AMPUTADO',

  MOBILIDADE_REDUZIDA = 'MOBILIDADE_REDUZIDA',

  LESAO_TEMPORARIA = 'LESAO_TEMPORARIA',

  SEM_LESAO = 'SEM_LESAO',

  OUTRO = 'OUTRO',
}
