export enum NivelAcesso {
  ADMINISTRADOR = 'ADMINISTRADOR',

  EQUIPE_TECNICA_REMOTA = 'EQUIPE_TECNICA_REMOTA',

  EQUIPE_TECNICA_PRESENCIAL = 'EQUIPE_TECNICA_PRESENCIAL',

  EQUIPE_LOGISTICA = 'EQUIPE_LOGISTICA',
}
